version: '3.8'
services:
  frontend:
    image: node:21-alpine
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app

  backend:
    image: your-golang-image
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/your-database-name
    # Add any other configurations for the Golang back-end here

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your-username
      - MONGO_INITDB_ROOT_PASSWORD=your-password
      - MONGO_INITDB_DATABASE=your-database-name

volumes:
  mongodb_data: